#!/bin/bash -l
#SBATCH --job-name=NAME
#SBATCH --qos="small"
#SBATCH -N 1
#SBATCH --ntasks-per-node=NTASKS
#SBATCH --output=OUT.out
#SBATCH --error=ERR.err
#SBATCH --time=TIME
#SBATCH --get-user-env

module purge
MODULES

BIN="command"
srun $BIN